---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.378.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.24.4
- name: go-task/task@v3.44.0
- name: editorconfig-checker/editorconfig-checker@v3.3.0
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.4.1
- name: suzuki-shunsuke/pinact@v3.2.0
- name: google/yamlfmt@v0.17.0
- name: k1LoW/octocov@v0.68.0
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.11.0
- name: securego/gosec@v2.22.4
- name: golangci/golangci-lint@v2.1.6
