---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.326.1 # renovate: depName=aquaproj/aqua-registry
packages:
- name: go-task/task@v3.42.1
- name: editorconfig-checker/editorconfig-checker@v3.2.1
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.2.3
- name: suzuki-shunsuke/pinact@v1.2.2
- name: google/yamlfmt@v0.16.0
- name: k1LoW/octocov@v0.64.0
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.11.0
- name: securego/gosec@v2.22.2
- name: dominikh/go-tools/staticcheck@2025.1.1
