---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.408.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.25.1
- name: go-task/task@v3.44.1
- name: editorconfig-checker/editorconfig-checker@v3.4.0
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.5.3
- name: suzuki-shunsuke/pinact@v3.4.2
- name: google/yamlfmt@v0.17.2
- name: k1LoW/octocov@v0.71.3
- name: koalaman/shellcheck@v0.11.0
- name: mvdan/sh@v3.12.0
- name: securego/gosec@v2.22.8
- name: golangci/golangci-lint@v2.4.0
