---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.289.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: go-task/task@v3.40.1
- name: editorconfig-checker/editorconfig-checker@v3.0.3
- name: rhysd/actionlint@v1.7.5
- name: suzuki-shunsuke/ghalint@v1.1.0
- name: suzuki-shunsuke/pinact@v1.1.2
- name: google/yamlfmt@v0.14.0
- name: k1LoW/octocov@v0.62.4
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.10.0
- name: securego/gosec@v2.21.4
- name: dominikh/go-tools/staticcheck@2024.1.1
