---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.308.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: go-task/task@v3.41.0
- name: editorconfig-checker/editorconfig-checker@v3.2.0
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.1.0
- name: suzuki-shunsuke/pinact@v1.2.1
- name: google/yamlfmt@v0.15.0
- name: k1LoW/octocov@v0.62.6
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.10.0
- name: securego/gosec@v2.22.0
- name: dominikh/go-tools/staticcheck@2024.1.1
