---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.361.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.24.2
- name: go-task/task@v3.43.3
- name: editorconfig-checker/editorconfig-checker@v3.2.1
- name: rhysd/actionlint@v1.7.7
- name: suzuki-shunsuke/ghalint@v1.3.0
- name: suzuki-shunsuke/pinact@v3.0.5
- name: google/yamlfmt@v0.16.0
- name: k1LoW/octocov@v0.67.0
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.11.0
- name: securego/gosec@v2.22.3
- name: golangci/golangci-lint@v2.1.6
