---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.468.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.26.0
- name: go-task/task@v3.48.0
- name: editorconfig-checker/editorconfig-checker@v3.6.1
- name: rhysd/actionlint@v1.7.10
- name: suzuki-shunsuke/ghalint@v1.5.5
- name: suzuki-shunsuke/pinact@v3.9.0
- name: google/yamlfmt@v0.21.0
- name: k1LoW/octocov@v0.74.5
- name: koalaman/shellcheck@v0.11.0
- name: mvdan/sh@v3.12.0
- name: securego/gosec@v2.22.11
- name: golangci/golangci-lint@v2.9.0
