---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.450.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: golang/go@go1.25.5
- name: go-task/task@v3.46.4
- name: editorconfig-checker/editorconfig-checker@v3.6.0
- name: rhysd/actionlint@v1.7.10
- name: suzuki-shunsuke/ghalint@v1.5.4
- name: suzuki-shunsuke/pinact@v3.8.0
- name: google/yamlfmt@v0.20.0
- name: k1LoW/octocov@v0.74.1
- name: koalaman/shellcheck@v0.11.0
- name: mvdan/sh@v3.12.0
- name: securego/gosec@v2.22.11
- name: golangci/golangci-lint@v2.7.2
