---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.219.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: go-task/task@v3.38.0
- name: editorconfig-checker/editorconfig-checker@v3.0.3
- name: rhysd/actionlint@v1.7.1
- name: suzuki-shunsuke/ghalint@v0.2.12
- name: suzuki-shunsuke/pinact@v0.2.1
- name: google/yamlfmt@v0.13.0
- name: k1LoW/octocov@v0.62.0
- name: koalaman/shellcheck@v0.10.0
- name: mvdan/sh@v3.9.0
- name: securego/gosec@v2.21.1
- name: dominikh/go-tools/staticcheck@2024.1.1
