---
central:
  badges:
    datastores:
    - local://badges
  push:
    enable: true
  reports:
    datastores:
    - artifact://takumin/boilerplate-golang-cli
    - artifact://takumin/octocov-central
    - artifact://takumin/path-action
