---
central:
  badges:
    datastores:
    - local://badges
  push:
    enable: false
  reports:
    datastores:
    - artifact://takumin/boilerplate-golang-cli
    - artifact://takumin/octocov-central
