---
central:
  badges:
    datastores:
    - local://badges
  reports:
    datastores:
    - artifact://takumin/ajimi
    - artifact://takumin/aptutil
    - artifact://takumin/boilerplate-golang-cli
    - artifact://takumin/manaita
    - artifact://takumin/octocov-central
    - artifact://takumin/rsdebstrap
