---
central:
  badges:
    datastores:
    - local://badges
  reports:
    datastores:
    - artifact://takumin/boilerplate-golang-cli
    - artifact://takumin/octocov-central
    - artifact://takumin/rsdebstrap
