---
# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
    - task: aqua
    - task: pinact
    - task: yamlfmt
    - task: editorconfig
    - task: actionlint
    - task: ghalint
    - task: shfmt
    - task: shellcheck
    - task: gosec
    - task: staticcheck

  aqua:
    run: once
    sources:
    - .aqua.yaml
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - aqua install --all
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  pinact:
    run: once
    deps: [aqua]
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - pinact run
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  yamlfmt:
    run: once
    deps: [aqua]
    sources:
    - '**/*.yml'
    - '**/*.yaml'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - yamlfmt .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  editorconfig:
    run: once
    deps: [aqua]
    sources:
    - '**/*'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ec
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  actionlint:
    run: once
    deps: [aqua]
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - actionlint
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  ghalint:
    run: once
    deps: [pinact]
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - ghalint run
    - ghalint act
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  shfmt:
    run: once
    deps: [aqua]
    sources:
    - '**/*.sh'
    - '**/*.bash'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - shfmt -w .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  shellcheck:
    run: once
    deps: [aqua]
    sources:
    - '**/*.sh'
    - '**/*.bash'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - for: sources
      cmd: shellcheck '{{.ITEM}}'
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  gosec:
    run: once
    deps: [aqua]
    sources:
    - 'go.work'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - gosec -quiet ./...
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  staticcheck:
    run: once
    deps: [aqua]
    sources:
    - 'go.work'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - staticcheck ./...
    - cmd: touch .task/.done_{{.TASK}}
      silent: true

  rewrite:
    run: once
    deps: [aqua]
    sources:
    - 'go.work'
    - '**/go.mod'
    - '**/go.sum'
    - '**/*.go'
    - exclude: '.git/**/*'
    - exclude: '.task/**/*'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - go run .
    - yamlfmt .
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
