---
name: Setup Aqua
description: Setup Aqua by using cache
runs:
  using: composite
  steps:
  - name: Aqua Tools Cache
    uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
    with:
      path: ~/.local/share/aquaproj-aqua
      key: aqua-tools-${{runner.os}}-${{runner.arch}}-${{hashFiles('.aqua.yaml')}}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
    with:
      aqua_version: v2.36.1
      aqua_opts: -a
