---
name: Setup Aqua
description: Setup Aqua by using cache
runs:
  using: composite
  steps:
  - name: Aqua Tools Cache
    uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
    with:
      path: ~/.local/share/aquaproj-aqua
      key: aqua-tools-${{runner.os}}-${{runner.arch}}-${{hashFiles('.aqua.yaml')}}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
    with:
      aqua_version: v2.36.1
      aqua_opts: -a
