---
name: Setup Aqua
description: Setup Aqua by using cache
runs:
  using: composite
  steps:
  - name: Aqua Tools Cache
    uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      path: ~/.local/share/aquaproj-aqua
      key: aqua-tools-${{runner.os}}-${{runner.arch}}-${{hashFiles('.aqua.yaml')}}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
    with:
      aqua_version: v2.42.1
      aqua_opts: -a
