---
name: Setup Aqua
description: Setup Aqua by using cache
runs:
  using: composite
  steps:
  - name: Aqua Tools Cache
    uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
    with:
      path: ~/.local/share/aquaproj-aqua
      key: aqua-tools-${{runner.os}}-${{runner.arch}}-${{hashFiles('.aqua.yaml')}}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
    with:
      aqua_version: v2.45.1
      aqua_opts: -a
