---
name: Integration Maintenance Task
on:
  push:
    branches:
    - main
  pull_request:
permissions:
  contents: read
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Running Task
      run: task
